buildVariable: false
familyName: Noto Serif Khitan Small Script
googleFonts: true
includeSubsets:
- from: Noto Serif
  name: GF_Latin_Core
recipeProvider: noto
sources:
- NotoSerifKhitanSmallScript.glyphspackage
